services:
  database:
    container_name: "tradepal-dev-db"
    image: postgres:16-alpine
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: "CMD-SHELL pg_isready -d $$POSTGRES_DB"
      interval: 1s
      timeout: 5s
      retries: 10

  api:
    container_name: "tradepal-api"
    depends_on:
      - database
    links:
      - database
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@tradepal-dev-db:5432/tradepal-db
    volumes:
      - ./src:/app/src
    ports:
      - '8080:8080'
volumes:
  db-data: