name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: tradepal-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma Client
      run: npx prisma generate

    - name: Run tests
      run: npm run test

    - name: Build application
      run: npm run build

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/chanflito/tradepal-api:latest

    - name: Deploy to VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: 22
        timeout: 60s
        command_timeout: 10m
        script: |
          set -e
          
          # Login to GitHub Container Registry
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # Pull the new image
          docker pull ghcr.io/chanflito/tradepal-api:latest
          
          # Navigate to project directory
          cd ~/tradepal
          
          # Stop current containers
          docker-compose -f docker-compose.prod.yml down || true
          
          # Start containers (IMAGE_TAG ya está configurado como default en docker-compose)
          docker-compose -f docker-compose.prod.yml up -d
          
          # Wait for containers to start
          echo "Waiting for containers to start..."
          sleep 30
          
          # Check deployment status
          if docker-compose -f docker-compose.prod.yml ps | grep -q "Up"; then
            echo "Containers are running"
            
            # Test API endpoint
            for i in {1..5}; do
              if curl -f http://localhost:8080 > /dev/null 2>&1; then
                echo "API is responding correctly"
                break
              else
                echo "API not ready, attempt $i/5..."
                sleep 10
              fi
            done
            
            # Clean up old images
            docker image prune -f || true
            echo "Deployment successful"
            
          else
            echo "Deployment failed - containers not running"
            docker-compose -f docker-compose.prod.yml ps
            docker-compose -f docker-compose.prod.yml logs --tail=50
            exit 1
          fi